version: "3"    # 버전 정보

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:          # 로컬 시스템의 볼륨을 어플리케이션을 실행할 docker 컨테이너로 매핑
      - ./app:/app    # 파일을 변경하면 자동으로 컨테이너에 업데이트되어 변경됨으로 Docker를 다시 시작할 필요가 없다.
    command: >        # 어플리케이션을 실행할 명령어, 모든 아이피 주소에서 접속 가능한 도커 실행
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:       # 1. DB가 app 보다 먼저 실행됨
      - db            # 2. 네트워크를 통해서 DB 서비스를 사용할 수 있음을 의미

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword # 실제 운영에서 사용할 패스워드는 넣지 않는다.
